services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/usr/src/app
    env_file:
      - .env
    depends_on:
      - database  
    command: ["npx", "ts-node", "src/index.ts"]
    restart: always 

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/src/app
    env_file:
      - .env
    depends_on:
      - backend
    restart: always   

  database:            
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}       # Variáveis lidas do .env
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
