services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    networks:
      - app-network
    volumes:
      - ./backend:/usr/src/app
    env_file:
      - .env
    depends_on:
      - database  
    command: ["npx", "ts-node", "src/index.ts"]

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    networks:
      - app-network
    environment:
      VITE_API_URL: "http://backend:8080"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    depends_on:
      - backend
    stdin_open: true
    tty: true

  database:            
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}       # Variáveis lidas do .env
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge